# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
deploy:
  stage: deploy
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - /usr/bin/rsync -av -e "ssh -o StrictHostKeyChecking=no" --delete ./public/ $SSH_USER@$SERVER_IP:~/sqlite-export-schema/html/
  artifacts:
    paths:
      - public
  only:
    - main
