image: "registry.roqua.nl/roqua/docker-base-images:ruby-2.6-builder"

deploy:
  stage: deploy
  before_script:
    - apk update && apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  script:
    - rsync -av -e "ssh -o StrictHostKeyChecking=no" --delete ./public/ $SSH_USER@$SERVER_IP:~/public_html/$NAME/
  artifacts:
    paths:
      - public
  only:
    - main
